config/routes.rb
Rails.application.routes.draw do

  get 'transactions/new'

  post 'transactions/create'

  devise_for :admins
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'products#index'

  get '/home', to: 'pages#home'
  post '/sendmail', to: 'pages#sendmail'

  resources :products, only: [:index, :show]

  resource :cart, only: [:show]

  post 'cart/:product_id', to: 'carts#add', as: 'add_to_cart'
  delete 'cart/:product_id', to: 'carts#remove', as: 'remove_from_cart'

  namespace :admin do
    resources :products
  end

  get '/apis/retrieve', to: 'apis#retrieve'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :user
  belongs_to :product

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user
  belongs_to :product

end

app/models/product.rb
class Product < ApplicationRecord

  has_many :orders
  has_many :cart_items

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :orders
  has_many :products, through: :orders

  has_many :cart_items

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def current_cart
    $redis.smembers "cart#{self.id}"
  end

  def purchase_cart_products!
    get_cart_products.each { |product| purchase(product) }
    $redis.del "cart#{id}"
  end

  def purchase(product)
    products << product unless purchase?(product)
  end

  def purchase?(product)
    products.include?(product)
  end

  def cart_total_price
    total_price = 0
    get_cart_products.each { |product| total_price+= product.price }
    total_price
  end

  def get_cart_products
    cart_ids = $redis.smembers "cart#{id}"
    Product.find(cart_ids)
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_action :authenticate_admin!

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController


  def index
  end

end

app/controllers/apis_controller.rb
class ApisController < ApplicationController

  # def retrieve
  #   response = Net::HTTP.get(URI('https://api.github.com/users/gohdaniel15'))
  #   @user = ActiveSupport::JSON.decode(response)
  #   render json: @user
  # end

  def retrieve
    @service = GetApiService.call
    render json: @service
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    if current_user
      cart_ids = $redis.smembers current_user_cart
    else
      cart_ids = session[:cart] || []
    end
    @products = Product.find(cart_ids)
  end

  def add
    if current_user
      $redis.sadd current_user_cart, params[:product_id]
    else
      session[:cart] ||= []
      session[:cart] << params[:product_id]
    end
    redirect_to products_path
  end

  def remove
    if current_user
      $redis.srem current_user_cart, params[:product_id]
    else
      session[:cart].delete(params[:product_id])
    end
    redirect_to products_path
  end

  private

  def current_user_cart
    "cart#{current_user.id}"
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_action :authenticate_user!

  def home
  end

  def sendmail
    UserMailer.welcome(current_user.email).deliver_later
    redirect_to home_path
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  before_action :authenticate_user!

  def new
    gon.client_token = generate_client_token
  end

  def create
    @result = Braintree::Transaction.sale(
      amount: current_user.cart_total_price,
      payment_method_nonce: params[:payment_method_nonce])
    if @result.success?
      current_user.purchase_cart_products!
      redirect_to root_url, notice: "Congratulations! Your transaction has been successfully!"
    else
      flash[:alert] = "Something went wrong while processing your transaction. Please try again!"
      gon.client_token = generate_client_token
      render :new
    end
  end

  private

  def generate_client_token
    Braintree::ClientToken.generate
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/application/_navbar.html.slim
ul.nav.justify-content-center
  - if current_user
    li.nav-item
      = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link'

app/views/carts/show.html.slim
= link_to 'Product index', products_path

table
  thead
    th Product Name
    th Product Price
    th

  tbody
    - @products.each do |product|
      tr
        td = product.name
        td = product.price
        td = link_to 'Remove from cart', remove_from_cart_path(product), method: :delete

= link_to "Checkout", transactions_new_path, class: "button"

app/views/layouts/application.html.slim
html
  head
    title ShoppingCartDemo

    = include_gon
    script[src="https://js.braintreegateway.com/v2/braintree.js"]

    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render partial: 'navbar'
    = yield

app/views/pages/home.html.slim
h2 Welcome to Shopping Cart Demo

= button_to 'Send Email', sendmail_path

app/views/products/index.html.slim
= link_to cart_path do
  = "Cart (#{current_user.current_cart.size})"

table
  thead
    th Product Name
    th Product Price
    th

  tbody
    - @products.each do |product|
      tr
        td = product.name
        td = product.price
        td = link_to 'Add to cart', add_to_cart_path(product), method: :post

app/views/transactions/create.html.slim
h1 Transactions#create
p Find me in app/views/transactions/create.html.slim

app/views/transactions/new.html.slim
.form-container
  h2.mbs New Transaction

  = form_tag transactions_create_path do

    p Please enter your payment details:

    #dropin

    = submit_tag "Pay #{current_user.cart_total_price}$", class: "button mt1"